### ISSUE TITLE
安装中间件，出现了如下问题

### ISSUE THREAD

**Issue by kettly1260** [catbaron0/efb-sticker2img-middleware#3]
Traceback (most recent call last):
  File "/usr/local/bin/ehforwarderbot", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/__main__.py", line 260, in main
    conf = config.load_config()
  File "/usr/local/lib/python3.6/dist-packages/ehforwarderbot/config.py", line 71, in load_config
    raise ValueError("\"%s\" is not found." % i)
ValueError: "catbaron.sticker2img" is not found.

**Comment by catbaron0** [comment]
看起来像是没安装成功。`python3 setup.py intall` 的时候没有报错么

**Comment by kettly1260** [comment]
> 看起来像是没安装成功。`python3 setup.py intall` 的时候没有报错么

解决了，之前没注意看，用的Python2了
