### ISSUE TITLE
utf-8' codec can't decode byte 0xca in position 252: invalid continuation byte

### ISSUE THREAD

**Issue by bao3** [catbaron0/efb-sticker2img-middleware#4]
如果我同时使用 efb-catbaron.link_preview 和  efb-sticker2img-middleware,就会出现错误。但是如果注释掉 sticker2img ，就可以完全正常启动。

Failed to get link preview: 'utf-8' codec can't decode byte 0xca in position 252: invalid continuation byte

```

ews-v2    |      All middlewares are initialized. 
ews-v2    | 2020-06-20 21:23:47,593 [ERROR]: plugins.catbaron.link_preview.MessageLinkPreviewMiddleware (__init__.process_message; __init__.py:188)
ews-v2    |     Failed to get link preview: 'utf-8' codec can't decode byte 0xca in position 252: invalid continuation byte
ews-v2    | 2020-06-20 21:24:00,110 [ERROR]: plugins.catbaron.link_preview.MessageLinkPreviewMiddleware (__init__.process_message; __init__.py:188)
ews-v2    |     Failed to get link preview: 'utf-8' codec can't decode byte 0xca in position 252: invalid continuation byte
Traceback (most recent call last):
ews-v2    |   File "/usr/bin/ehforwarderbot", line 11, in <module>
ews-v2    |     load_entry_point('ehforwarderbot==2.0.0', 'console_scripts', 'ehforwarderbot')()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 268, in main
ews-v2    |     conf = config.load_config()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/config.py", line 73, in load_config
ews-v2    |     middleware = utils.locate_module(i, 'middleware')
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/utils.py", line 145, in locate_module
ews-v2    |     return i.load()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
ews-v2    |     return self.resolve()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
ews-v2    |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ews-v2    |   File "<frozen zipimport>", line 259, in load_module
ews-v2    |   File "/usr/lib/python3.8/site-packages/efb_sticker2img_middleware-0.0.1-py3.8.egg/efb_sticker2img_middleware/__init__.py", line 8, in <module>
ews-v2    | ImportError: cannot import name 'EFBMiddleware' from 'ehforwarderbot' (/usr/lib/python3.8/site-packages/ehforwarderbot/__init__.py)
Traceback (most recent call last):
ews-v2    |   File "/usr/bin/ehforwarderbot", line 11, in <module>
ews-v2    |     load_entry_point('ehforwarderbot==2.0.0', 'console_scripts', 'ehforwarderbot')()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 268, in main
ews-v2    |     conf = config.load_config()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/config.py", line 73, in load_config
ews-v2    |     middleware = utils.locate_module(i, 'middleware')
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/utils.py", line 145, in locate_module
master_channel: blueset.telegram
ews-v2    |     return i.load()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
ews-v2    |     return self.resolve()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
ews-v2    |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ews-v2    |   File "<frozen zipimport>", line 259, in load_module
ews-v2    |   File "/usr/lib/python3.8/site-packages/efb_sticker2img_middleware-0.0.1-py3.8.egg/efb_sticker2img_middleware/__init__.py", line 8, in <module>
ews-v2    | ImportError: cannot import name 'EFBMiddleware' from 'ehforwarderbot' (/usr/lib/python3.8/site-packages/ehforwarderbot/__init__.py)
Traceback (most recent call last):
ews-v2    |   File "/usr/bin/ehforwarderbot", line 11, in <module>
ews-v2    |     load_entry_point('ehforwarderbot==2.0.0', 'console_scripts', 'ehforwarderbot')()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 268, in main
ews-v2    |     conf = config.load_config()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/config.py", line 73, in load_config
ews-v2    |     middleware = utils.locate_module(i, 'middleware')
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/utils.py", line 145, in locate_module
ews-v2    |     return i.load()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
ews-v2    |     return self.resolve()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve

ews-v2    |     middleware = utils.locate_module(i, 'middleware')
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/utils.py", line 145, in locate_module
ews-v2    |     return i.load()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
ews-v2    |     return self.resolve()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
ews-v2    |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ews-v2    |   File "<frozen zipimport>", line 259, in load_module
ews-v2    |   File "/usr/lib/python3.8/site-packages/efb_sticker2img_middleware-0.0.1-py3.8.egg/efb_sticker2img_middleware/__init__.py", line 8, in <module>
ews-v2    | ImportError: cannot import name 'EFBMiddleware' from 'ehforwarderbot' (/usr/lib/python3.8/site-packages/ehforwarderbot/__init__.py)
Traceback (most recent call last):
ews-v2    |   File "/usr/bin/ehforwarderbot", line 11, in <module>
ews-v2    |     load_entry_point('ehforwarderbot==2.0.0', 'console_scripts', 'ehforwarderbot')()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/__main__.py", line 268, in main
ews-v2    |     conf = config.load_config()
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/config.py", line 73, in load_config
ews-v2    |     middleware = utils.locate_module(i, 'middleware')
ews-v2    |   File "/usr/lib/python3.8/site-packages/ehforwarderbot/utils.py", line 145, in locate_module
ews-v2    |     return i.load()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
ews-v2    |     return self.resolve()
ews-v2    |   File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
ews-v2    |     module = __import__(self.module_name, fromlist=['__name__'], level=0)
ews-v2    |   File "<frozen zipimport>", line 259, in load_module
ews-v2    |   File "/usr/lib/python3.8/site-packages/efb_sticker2img_middleware-0.0.1-py3.8.egg/efb_sticker2img_middleware/__init__.py", line 8, in <module>
ews-v2    | ImportError: cannot import name 'EFBMiddleware' from 'ehforwarderbot' (/usr/lib/python3.8/site-packages/ehforwarderbot/__init__.py)
[root@LA efb-wechat]# 


```

**Comment by catbaron0** [comment]
这个中间件的功能已经被集成到 ETM 中，所以已经不需要单独启用。
